### ISSUE TITLE
Nested hook calls don't seem to be possible

### ISSUE THREAD

**Issue by alexandermckay** [TrueFit/bach#13]
Nested hook calls are possible using React. However I cannot figure out a way to do so with the `bach` library.

I have created an [example](https://codesandbox.io/s/small-night-rcvpc?file=/src/App.tsx) showing exactly what I mean by nesting. 

In the `app.tsx` file there are two components being rendered: `Hooks` and `Bach`. 

They both do the same thing however the implementation is done with vanilla hooks and bach respectively. If you uncomment the `Bach` component you will see that compilation breaks (due to `"breaking a hook rule"`). 

Whilst this example is contrived, I often find myself organising a number of hooks within a single hook to reduce noise within a component. Is this a limitation of the library or a failure of implementation on my behalf?

**Comment by jgretz** [comment]
Assuming you are using the code from your other github issue (https://codesandbox.io/s/cocky-wave-81ur4)

Those errors are actually eslint not bach, typescript or react. These are because you are using the naming convention "use" for your methods which is reserved for hooks. 

You can either continue doing this and use the "withHook" enhancer or change your name to an appropriately named function.
